CREATE DATABASE IF NOT EXISTS BookApplication;

USE bookapplication;

DROP TABLE IF EXISTS BookChapter;

DROP TABLE IF EXISTS FootNote;

DROP TABLE IF EXISTS Book;

CREATE TABLE IF NOT EXISTS Book(
                                   BCode INT AUTO_INCREMENT,
                                   BName VARCHAR(50) NOT NULL,
    AName VARCHAR(50) NOT NULL,
    PRIMARY KEY (Bcode)
    );

CREATE TABLE IF NOT EXISTS BookChapter(
                                          BCode INT NOT NULL,
                                          CNum INT NOT NULL,
                                          CTitle VARCHAR(50) NOT NULL,
    CContent TEXT NOT NULL,
    FOREIGN KEY (Bcode) REFERENCES Book(BCode) ON UPDATE CASCADE ON DELETE CASCADE
    );

CREATE TABLE FootNote(
                         BCode INT NOT NULL,
                         FCode INT,
                         FContent TEXT,
                         FOREIGN KEY (Bcode) REFERENCES Book(BCode) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO Book (BName, AName) VALUES('Casablanca', 'David Graham');

INSERT INTO Book (BName, AName) VALUES('Burn Out', 'Jones Hamilton');

INSERT INTO Book (BName, AName) VALUES('German', 'Larry');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(1, 1, 'Shadow',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(1, 2, 'Light',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(1, 3, 'Sun',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(1, 4, 'Noon',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(1, 5, 'Day',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(1, 6, 'IDK',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(2, 1, 'Apple',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(2, 2, 'Banana',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(2, 3, 'Kiwi',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(2, 4, 'Blueberry',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(2, 5, 'Strawberry',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO BookChapter(BCode, CNum, CTitle, CContent) VALUES(2, 6, 'Mango',  '<p> <b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Mauris purus augue, aliquam at facilisis eget, elementum ac enim. Aliquam id libero nec eros pulvinar iaculis. Sed pharetra elit nec libero maximus auctor. Sed finibus varius felis, in accumsan arcu finibus semper. Praesent consequat sem massa, ut lobortis nibh sodales nec. Sed ut neque non quam congue vestibulum sit amet non erat. Pellentesque congue elit eleifend, scelerisque sem sit amet, ornare mi. Suspendisse aliquam elit vel dui finibus, eget rhoncus lectus facilisis. Ut vulputate enim ut augue luctus faucibus. Donec posuere nisl nec nibh iaculis imperdiet. Sed justo odio, varius nec metus eget, sodales accumsan arcu. Praesent vitae fermentum velit, eget congue eros. Suspendisse non neque odio. Maecenas vitae turpis sed turpis venenatis egestas. Sed euismod accumsan velit, vitae sollicitudin nisi. Praesent a nulla semper, faucibus lacus sed, faucibus enim. Fusce ipsum mi, sagittis sed magna a, ultrices sodales velit.Praesent luctus tortor vitae turpis ullamcorper vestibulum. Pellentesque a quam leo. Fusce dolor lacus, tempus nec elementum eu, hendrerit non augue. Maecenas vehicula nisl est, ac dictum nulla convallis vitae. Etiam non consequat augue, et venenatis eros. Pellentesque vitae nulla vitae dui convallis tristique nec sit amet odio. Praesent lobortis nibh eu egestas pulvinar. Proin in finibus sapien, ut fringilla leo. Maecenas magna neque, tempus ut posuere eget, interdum quis augue. Nullam elementum ex ultrices nunc venenatis pulvinar. Phasellus rutrum est eget nisi pulvinar, ac condimentum felis tincidunt. Curabitur non ante sit amet leo dictum tincidunt pellentesque et libero. In hac habitasse platea dictumst.
Integer eget dolor tristique, commodo neque in, ultricies sapien. Donec non nisi non dui <i> vestibulum congue </i>. <i><b>Morbi purus neque </b></i>, dignissim sed sodales non, dapibus condimentum ex. Phasellus eget malesuada magna. In vel erat ut odio pretium congue. Donec pellentesque blandit ex nec interdum. Vestibulum interdum risus vitae libero commodo, quis consequat odio varius. Morbi varius maximus pretium. Pellentesque sodales tellus lectus, nec interdum lorem rhoncus sit amet. Vestibulum quis interdum neque, id sollicitudin quam. Donec non fermentum est, in cursus lorem. Proin fringilla nibh mauris, quis rutrum dui porttitor nec. Mauris consequat ex sed sapien ornare, suscipit varius quam tempor. Integer non tempor diam. Morbi blandit diam sed tellus accumsan porttitor. Suspendisse erat diam, lacinia ut lacus sed, faucibus pharetra eros. Nam gravida rutrum gravida.</p>');

INSERT INTO bookchapter VALUES ('3','1','Ein','aaaaaaaaaaaaaaa');
INSERT INTO bookchapter VALUES ('3','2','Zwei','aaaaaaaaaaaaaaa');

INSERT INTO footnote VALUES ('1','1','A - Apple');
INSERT INTO footnote VALUES ('2','1','B - Banana');
INSERT INTO footnote VALUES ('2','2','C - Cherry');
INSERT INTO footnote VALUES ('3','1','D - Doritos');
INSERT INTO footnote VALUES ('3','2','E - Egg');